/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  about_video: () => import("@/views/about/video/index.vue"),
  alert_config: () => import("@/views/alert/config/index.vue"),
  alert_info: () => import("@/views/alert/info/index.vue"),
  alert_log: () => import("@/views/alert/log/index.vue"),
  alert_rules: () => import("@/views/alert/rules/index.vue"),
  bigscreen: () => import("@/views/bigscreen/index.vue"),
  customer_config: () => import("@/views/customer/config/index.vue"),
  customer_data: () => import("@/views/customer/data/index.vue"),
  customer_interface: () => import("@/views/customer/interface/index.vue"),
  device_config: () => import("@/views/device/config/index.vue"),
  device_info: () => import("@/views/device/info/index.vue"),
  device_message: () => import("@/views/device/message/index.vue"),
  device_user: () => import("@/views/device/user/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_multi-tab": () => import("@/views/function/multi-tab/index.vue"),
  function_request: () => import("@/views/function/request/index.vue"),
  "function_super-page": () => import("@/views/function/super-page/index.vue"),
  function_tab: () => import("@/views/function/tab/index.vue"),
  "function_toggle-auth": () => import("@/views/function/toggle-auth/index.vue"),
  geofence: () => import("@/views/geofence/index.vue"),
  health_ai: () => import("@/views/health/ai/index.vue"),
  health_analysis: () => import("@/views/health/analysis/index.vue"),
  health_baseline: () => import("@/views/health/baseline/index.vue"),
  health_chart: () => import("@/views/health/chart/index.vue"),
  health_config: () => import("@/views/health/config/index.vue"),
  health_echarts: () => import("@/views/health/echarts/index.vue"),
  health_info: () => import("@/views/health/info/index.vue"),
  health_profile: () => import("@/views/health/profile/index.vue"),
  health_score: () => import("@/views/health/score/index.vue"),
  home: () => import("@/views/home/index.vue"),
  job: () => import("@/views/job/index.vue"),
  manage_dict: () => import("@/views/manage/dict/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_notice: () => import("@/views/manage/notice/index.vue"),
  manage_org: () => import("@/views/manage/org/index.vue"),
  manage_position: () => import("@/views/manage/position/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  map: () => import("@/views/map/index.vue"),
  monitor_cache: () => import("@/views/monitor/cache/index.vue"),
  monitor_file: () => import("@/views/monitor/file/index.vue"),
  monitor_logs_error: () => import("@/views/monitor/logs_error/index.vue"),
  monitor_logs_login: () => import("@/views/monitor/logs_login/index.vue"),
  monitor_logs_operation: () => import("@/views/monitor/logs_operation/index.vue"),
  monitor_logs_scheduler: () => import("@/views/monitor/logs_scheduler/index.vue"),
  monitor_scheduler: () => import("@/views/monitor/scheduler/index.vue"),
  monitor_system: () => import("@/views/monitor/system/index.vue"),
  "multi-menu_first_child": () => import("@/views/multi-menu/first_child/index.vue"),
  "multi-menu_second_child_home": () => import("@/views/multi-menu/second_child_home/index.vue"),
  task: () => import("@/views/task/index.vue"),
  "tools_generate-table": () => import("@/views/tools/generate-table/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
