/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 999
    },
    children: [
      {
        name: 'about_video',
        path: '/about/video',
        component: 'view.about_video',
        meta: {
          title: 'about_video',
          i18nKey: 'route.about_video'
        }
      }
    ]
  },
  {
    name: 'alert',
    path: '/alert',
    component: 'layout.base',
    meta: {
      title: 'alert',
      i18nKey: 'route.alert'
    },
    children: [
      {
        name: 'alert_config',
        path: '/alert/config',
        meta: {
          title: 'alert_config',
          i18nKey: 'route.alert_config'
        },
        children: [
          {
            name: 'alert_config_wechat',
            path: '/alert/config/wechat',
            component: 'view.alert_config_wechat',
            meta: {
              title: 'alert_config_wechat',
              i18nKey: 'route.alert_config_wechat'
            }
          }
        ]
      },
      {
        name: 'alert_info',
        path: '/alert/info',
        component: 'view.alert_info',
        meta: {
          title: 'alert_info',
          i18nKey: 'route.alert_info'
        }
      },
      {
        name: 'alert_log',
        path: '/alert/log',
        component: 'view.alert_log',
        meta: {
          title: 'alert_log',
          i18nKey: 'route.alert_log'
        }
      },
      {
        name: 'alert_rules',
        path: '/alert/rules',
        component: 'view.alert_rules',
        meta: {
          title: 'alert_rules',
          i18nKey: 'route.alert_rules'
        }
      }
    ]
  },
  {
    name: 'bigscreen',
    path: '/bigscreen',
    component: 'layout.base$view.bigscreen',
    meta: {
      title: 'bigscreen',
      i18nKey: 'route.bigscreen',
      openInNewWindow: true
    }
  },
  {
    name: 'customer',
    path: '/customer',
    component: 'layout.base',
    meta: {
      title: 'customer',
      i18nKey: 'route.customer'
    },
    children: [
      {
        name: 'customer_config',
        path: '/customer/config',
        component: 'view.customer_config',
        meta: {
          title: 'customer_config',
          i18nKey: 'route.customer_config'
        }
      },
      {
        name: 'customer_data',
        path: '/customer/data',
        component: 'view.customer_data',
        meta: {
          title: 'customer_data',
          i18nKey: 'route.customer_data'
        }
      },
      {
        name: 'customer_interface',
        path: '/customer/interface',
        component: 'view.customer_interface',
        meta: {
          title: 'customer_interface',
          i18nKey: 'route.customer_interface'
        }
      }
    ]
  },
  {
    name: 'device',
    path: '/device',
    component: 'layout.base',
    meta: {
      title: 'device',
      i18nKey: 'route.device'
    },
    children: [
      {
        name: 'device_bind',
        path: '/device/bind',
        component: 'view.device_bind',
        meta: {
          title: 'device_bind',
          i18nKey: 'route.device_bind',
          roles: ['R_ADMIN'],
          icon: 'ic:round-link',
          order: 1
        }
      },
      {
        name: 'device_config',
        path: '/device/config',
        component: 'view.device_config',
        meta: {
          title: 'device_config',
          i18nKey: 'route.device_config'
        }
      },
      {
        name: 'device_info',
        path: '/device/info',
        component: 'view.device_info',
        meta: {
          title: 'device_info',
          i18nKey: 'route.device_info'
        }
      },
      {
        name: 'device_message',
        path: '/device/message',
        component: 'view.device_message',
        meta: {
          title: 'device_message',
          i18nKey: 'route.device_message'
        }
      },
      {
        name: 'device_user',
        path: '/device/user',
        component: 'view.device_user',
        meta: {
          title: 'device_user',
          i18nKey: 'route.device_user'
        }
      }
    ]
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 6
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child',
          icon: 'material-symbols:filter-list-off',
          order: 2
        },
        redirect: '/function/hide-child/one',
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one',
              icon: 'material-symbols:filter-list-off',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab',
          icon: 'ic:round-tab',
          multiTab: true,
          hideInMenu: true,
          activeMenu: 'function_tab'
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request',
          icon: 'carbon:network-overlay',
          order: 3
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page',
          icon: 'ic:round-supervisor-account',
          order: 5,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab',
          icon: 'ic:round-tab',
          order: 1
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth',
          icon: 'ic:round-construction',
          order: 4
        }
      }
    ]
  },
  {
    name: 'geofence',
    path: '/geofence',
    component: 'layout.base$view.geofence',
    meta: {
      title: 'geofence',
      i18nKey: 'route.geofence'
    }
  },
  {
    name: 'health',
    path: '/health',
    component: 'layout.base',
    meta: {
      title: 'health',
      i18nKey: 'route.health'
    },
    children: [
      {
        name: 'health_ai',
        path: '/health/ai',
        component: 'view.health_ai',
        meta: {
          title: 'health_ai',
          i18nKey: 'route.health_ai'
        }
      },
      {
        name: 'health_analysis',
        path: '/health/analysis',
        component: 'view.health_analysis',
        meta: {
          title: 'health_analysis',
          i18nKey: 'route.health_analysis'
        }
      },
      {
        name: 'health_baseline',
        path: '/health/baseline',
        component: 'view.health_baseline',
        meta: {
          title: 'health_baseline',
          i18nKey: 'route.health_baseline'
        }
      },
      {
        name: 'health_chart',
        path: '/health/chart',
        component: 'view.health_chart',
        meta: {
          title: 'health_chart',
          i18nKey: 'route.health_chart'
        }
      },
      {
        name: 'health_config',
        path: '/health/config',
        component: 'view.health_config',
        meta: {
          title: 'health_config',
          i18nKey: 'route.health_config'
        }
      },
      {
        name: 'health_echarts',
        path: '/health/echarts',
        component: 'view.health_echarts',
        meta: {
          title: 'health_echarts',
          i18nKey: 'route.health_echarts'
        }
      },
      {
        name: 'health_info',
        path: '/health/info',
        component: 'view.health_info',
        meta: {
          title: 'health_info',
          i18nKey: 'route.health_info'
        }
      },
      {
        name: 'health_profile',
        path: '/health/profile',
        component: 'view.health_profile',
        meta: {
          title: 'health_profile',
          i18nKey: 'route.health_profile'
        }
      },
      {
        name: 'health_score',
        path: '/health/score',
        component: 'view.health_score',
        meta: {
          title: 'health_score',
          i18nKey: 'route.health_score'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'job',
    path: '/job',
    component: 'layout.base$view.job',
    meta: {
      title: 'job',
      i18nKey: 'route.job'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_notice',
        path: '/manage/notice',
        component: 'view.manage_notice',
        meta: {
          title: 'manage_notice',
          i18nKey: 'route.manage_notice'
        }
      },
      {
        name: 'manage_org',
        path: '/manage/org',
        component: 'view.manage_org',
        meta: {
          title: 'manage_org',
          i18nKey: 'route.manage_org'
        }
      },
      {
        name: 'manage_position',
        path: '/manage/position',
        component: 'view.manage_position',
        meta: {
          title: 'manage_position',
          i18nKey: 'route.manage_position'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'map',
    path: '/map',
    component: 'layout.base$view.map',
    meta: {
      title: 'map',
      i18nKey: 'route.map'
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_file',
        path: '/monitor/file',
        component: 'view.monitor_file',
        meta: {
          title: 'monitor_file',
          i18nKey: 'route.monitor_file'
        }
      },
      {
        name: 'monitor_logs',
        path: '/monitor/logs',
        meta: {
          title: 'monitor_logs',
          i18nKey: 'route.monitor_logs'
        },
        children: [
          {
            name: 'monitor_logs_error',
            path: '/monitor/logs/error',
            component: 'view.monitor_logs_error',
            meta: {
              title: 'monitor_logs_error',
              i18nKey: 'route.monitor_logs_error'
            }
          },
          {
            name: 'monitor_logs_login',
            path: '/monitor/logs/login',
            component: 'view.monitor_logs_login',
            meta: {
              title: 'monitor_logs_login',
              i18nKey: 'route.monitor_logs_login'
            }
          },
          {
            name: 'monitor_logs_operation',
            path: '/monitor/logs/operation',
            component: 'view.monitor_logs_operation',
            meta: {
              title: 'monitor_logs_operation',
              i18nKey: 'route.monitor_logs_operation'
            }
          },
          {
            name: 'monitor_logs_scheduler',
            path: '/monitor/logs/scheduler',
            component: 'view.monitor_logs_scheduler',
            meta: {
              title: 'monitor_logs_scheduler',
              i18nKey: 'route.monitor_logs_scheduler'
            }
          }
        ]
      },
      {
        name: 'monitor_scheduler',
        path: '/monitor/scheduler',
        component: 'view.monitor_scheduler',
        meta: {
          title: 'monitor_scheduler',
          i18nKey: 'route.monitor_scheduler'
        }
      },
      {
        name: 'monitor_system',
        path: '/monitor/system',
        component: 'view.monitor_system',
        meta: {
          title: 'monitor_system',
          i18nKey: 'route.monitor_system'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      order: 8
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first',
          order: 1
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second',
          order: 2
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'task',
    path: '/task',
    component: 'layout.base$view.task',
    meta: {
      title: 'task',
      i18nKey: 'route.task'
    }
  },
  {
    name: 'tools',
    path: '/tools',
    component: 'layout.base',
    meta: {
      title: 'tools',
      i18nKey: 'route.tools'
    },
    children: [
      {
        name: 'tools_generate-table',
        path: '/tools/generate-table',
        component: 'view.tools_generate-table',
        meta: {
          title: 'tools_generate-table',
          i18nKey: 'route.tools_generate-table'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true,
      constant: true
    }
  }
];
