#!/bin/bash
# 加载LJWX配置的简单脚本

# 加载配置文件
source ljwx.env

echo "🔧 LJWX配置已加载："
echo "   Registry: $REGISTRY"
echo "   MySQL: $MYSQL_HOST:$MYSQL_PORT ($MYSQL_USERNAME/$MYSQL_PASSWORD)"
echo "   Redis: $REDIS_HOST:$REDIS_PORT"
echo "   服务端口: Admin:$ADMIN_PORT, Bigscreen:$BIGSCREEN_PORT, Boot:$BOOT_PORT"

# 导出所有变量供其他脚本使用
export REGISTRY MYSQL_VERSION REDIS_VERSION BOOT_VERSION BIGSCREEN_VERSION ADMIN_VERSION
export MYSQL_HOST MYSQL_PORT MYSQL_DATABASE MYSQL_USERNAME MYSQL_PASSWORD
export REDIS_HOST REDIS_PORT REDIS_PASSWORD
export ADMIN_PORT BIGSCREEN_PORT BOOT_PORT NETWORK_NAME