"""
数据库模型定义 - 基于实际数据库表结构
"""
from sqlalchemy import Column, BigInteger, Integer, String, DateTime, Double, Decimal, Text, JSON, Enum, Boolean
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime
from typing import Optional

Base = declarative_base()

class UserHealthData(Base):
    """用户健康数据表"""
    __tablename__ = "t_user_health_data"
    
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    phone_number = Column(String(20))
    heart_rate = Column(Integer)
    pressure_high = Column(Integer) 
    pressure_low = Column(Integer)
    blood_oxygen = Column(Integer)
    stress = Column(Integer)
    temperature = Column(Double(5, 2))
    step = Column(Integer)
    timestamp = Column(DateTime, nullable=False, default=datetime.now)
    user_name = Column(String(255), nullable=False, default="heguang")
    latitude = Column(Decimal(10, 6))
    longitude = Column(Decimal(10, 6))
    altitude = Column(Double)
    device_sn = Column(String(255), nullable=False)
    distance = Column(Double)
    calorie = Column(Double)
    is_deleted = Column(Boolean, nullable=False, default=False)
    create_user = Column(String(255))
    create_user_id = Column(BigInteger)
    create_time = Column(DateTime, nullable=False, default=datetime.now)
    update_user = Column(String(255))
    update_user_id = Column(BigInteger)
    update_time = Column(DateTime, nullable=False, default=datetime.now)
    upload_method = Column(Enum('wifi', 'bluetooth', 'common_event', 'esim'), nullable=False, default='wifi')
    user_id = Column(BigInteger)
    org_id = Column(BigInteger)
    sleep = Column(Double)
    customer_id = Column(BigInteger, nullable=False, default=0)

class AlertInfo(Base):
    """告警信息表"""
    __tablename__ = "t_alert_info"
    
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    rule_id = Column(BigInteger, nullable=False)
    rule_version = Column(BigInteger)
    trigger_conditions = Column(JSON)
    evaluation_context = Column(JSON)
    suppression_key = Column(String(128))
    escalation_level = Column(Integer, default=0)
    ack_required = Column(Boolean, default=False)
    auto_resolve = Column(Boolean, default=False)
    alert_type = Column(String(100), nullable=False)
    device_sn = Column(String(20), nullable=False)
    alert_timestamp = Column(DateTime, default=datetime.now)
    alert_desc = Column(String(2000))
    severity_level = Column(String(50), nullable=False, default="medium")
    alert_status = Column(String(50), default="pending")
    assigned_user = Column(String(255))
    assigned_user_id = Column(BigInteger)
    is_deleted = Column(Boolean, default=False)
    create_user = Column(String(255))
    create_user_id = Column(BigInteger)
    create_time = Column(DateTime, default=datetime.now)
    update_user = Column(String(255))
    update_user_id = Column(BigInteger)
    update_time = Column(DateTime, default=datetime.now)
    longitude = Column(Decimal(12, 8), default=22.54036796)
    latitude = Column(Decimal(12, 8), default=114.01508952)
    altitude = Column(Decimal(10, 2), default=0.00)
    health_id = Column(BigInteger)
    user_id = Column(BigInteger)
    org_id = Column(BigInteger)
    customer_id = Column(BigInteger, nullable=False, default=0)
    responded_time = Column(DateTime)
    response_duration = Column(Integer)
    source = Column(String(16), nullable=False, default="server")
    event_type = Column(String(64))
    metric = Column(String(64))
    value = Column(Double)
    unit = Column(String(16))
    level = Column(String(16), nullable=False, default="minor")
    status = Column(String(24), nullable=False, default="NEW")
    dedup_key = Column(String(128))
    throttle_until = Column(DateTime)
    occur_at = Column(DateTime, nullable=False, default=datetime.now)
    recover_at = Column(DateTime)
    assigned_to = Column(String(64))
    extend = Column(JSON)
    due_time = Column(DateTime)
    auto_close_time = Column(DateTime)
    auto_processed = Column(Boolean, default=False)
    auto_process_time = Column(DateTime)
    auto_process_reason = Column(Text)
    processing_stage = Column(Enum('NEW', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'SUPPRESSED', 'ESCALATED'), default='NEW')
    resolution_notes = Column(Text)
    suppression_reason = Column(Text)
    suppression_until = Column(DateTime)
    acknowledgment_time = Column(DateTime)
    acknowledgment_user = Column(BigInteger)
    priority = Column(Integer, default=3)

class DeviceInfo(Base):
    """设备信息表"""
    __tablename__ = "t_device_info"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    system_software_version = Column(String(255), nullable=False)
    wifi_address = Column(String(255))
    bluetooth_address = Column(String(255))
    ip_address = Column(String(255))
    network_access_mode = Column(String(10))
    serial_number = Column(String(255), unique=True)
    device_name = Column(String(255))
    imei = Column(String(255))
    created_at = Column(DateTime, default=datetime.now)
    battery_level = Column(Integer)
    model = Column(String(50))
    status = Column(Enum('INACTIVE', 'ACTIVE'))
    wearable_status = Column(Enum('WORN', 'NOT_WORN'))
    charging_status = Column(Enum('NOT_CHARGING', 'CHARGING'))
    is_deleted = Column(Boolean, default=False)
    create_user = Column(String(255))
    create_user_id = Column(BigInteger)
    create_time = Column(DateTime)
    update_user = Column(String(255))
    update_user_id = Column(BigInteger)
    update_time = Column(DateTime)
    timestamp = Column(DateTime, nullable=False)
    voltage = Column(Integer)
    user_id = Column(BigInteger)
    org_id = Column(BigInteger)
    customer_id = Column(BigInteger, nullable=False, default=0)

class SysUser(Base):
    """系统用户表"""
    __tablename__ = "sys_user"
    
    id = Column(BigInteger, primary_key=True)
    user_name = Column(String(40), nullable=False, unique=True)
    password = Column(String(100), nullable=False)
    nick_name = Column(String(20))
    real_name = Column(String(20), nullable=False)
    avatar = Column(String(200))
    email = Column(String(45), nullable=False)
    phone = Column(String(45))
    gender = Column(String(2), default="0")
    create_user = Column(String(40), nullable=False)
    create_user_id = Column(BigInteger, nullable=False)
    create_time = Column(DateTime, nullable=False)
    update_user = Column(String(40))
    update_user_id = Column(BigInteger)
    update_time = Column(DateTime)
    salt = Column(String(6))
    last_login_time = Column(DateTime)
    update_password_time = Column(DateTime)
    status = Column(String(2), default="1")
    is_deleted = Column(Boolean, default=False)
    device_sn = Column(String(50))
    customer_id = Column(BigInteger, nullable=False, default=0)
    user_card_number = Column(String(50))
    working_years = Column(Integer, default=0)
    org_id = Column(BigInteger)
    org_name = Column(String(100))
    birthday = Column(DateTime)
    user_type = Column(Integer, default=0)
    admin_level = Column(Integer, default=0)

class DeviceMessage(Base):
    """设备消息表"""
    __tablename__ = "t_device_message"
    
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    message_id = Column(String(64), nullable=False, unique=True)
    customer_id = Column(BigInteger, nullable=False)
    org_id = Column(BigInteger)
    user_id = Column(String(64))
    device_sn = Column(String(128))
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    message_type = Column(Enum('NOTIFICATION', 'ALERT', 'WARNING', 'INFO', 'EMERGENCY', 'JOB', 'TASK'), 
                         nullable=False, default='NOTIFICATION')
    sender_type = Column(Enum('SYSTEM', 'USER', 'DEVICE', 'API'), nullable=False, default='SYSTEM')
    receiver_type = Column(Enum('USER', 'DEVICE', 'GROUP', 'BROADCAST'), nullable=False, default='USER')
    urgency = Column(Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'), nullable=False, default='MEDIUM')
    priority_level = Column(Integer, default=3)
    message_status = Column(Enum('DRAFT', 'PENDING', 'SENT', 'DELIVERED', 'ACKNOWLEDGED', 'FAILED', 'EXPIRED'), 
                           nullable=False, default='PENDING')
    channels = Column(JSON)
    require_ack = Column(Boolean, default=False)
    metadata = Column(JSON)
    sent_time = Column(DateTime)
    received_time = Column(DateTime)
    acknowledged_time = Column(DateTime)
    expires_at = Column(DateTime)
    responded_number = Column(Integer, default=0)
    target_count = Column(Integer, default=0)
    is_deleted = Column(Boolean, nullable=False, default=False)
    create_time = Column(DateTime, nullable=False, default=datetime.now)
    update_time = Column(DateTime, nullable=False, default=datetime.now)
    create_user = Column(String(64))
    update_user = Column(String(64))
    version = Column(Integer, default=1)