name: ðŸ³ Docker æž„å»ºæµ‹è¯•

on:
  push:
    branches: [ main ]

env:
  REGISTRY_URL: 'localhost:5001'

jobs:
  build:
    name: ðŸ—ï¸ æž„å»ºé•œåƒ
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ä»£ç 
        uses: actions/checkout@v4
      
      - name: åˆ›å»ºæµ‹è¯• Dockerfile
        run: |
          cat > Dockerfile << 'EOF_DOCKERFILE'
          FROM nginx:alpine
          COPY . /usr/share/nginx/html/
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]
          EOF_DOCKERFILE
      
      - name: æž„å»º Docker é•œåƒ
        run: |
          docker build -t ${{ env.REGISTRY_URL }}/test-app:${{ github.sha }} .
          docker build -t ${{ env.REGISTRY_URL }}/test-app:latest .
      
      - name: æŽ¨é€åˆ°ç§æœ‰ä»“åº“
        run: |
          docker push ${{ env.REGISTRY_URL }}/test-app:${{ github.sha }}
          docker push ${{ env.REGISTRY_URL }}/test-app:latest
          
          echo "âœ… é•œåƒæŽ¨é€å®Œæˆ"
          echo "ðŸ“¦ é•œåƒ: ${{ env.REGISTRY_URL }}/test-app:latest"
