FROM python:3.9-slim
WORKDIR /app
COPY requirements-docker.txt .
RUN pip install --no-cache-dir -r requirements-docker.txt
COPY . .
ENV MYSQL_HOST=host.docker.internal MYSQL_PORT=3306 REDIS_HOST=host.docker.internal REDIS_PORT=6379 PYTHONPATH=/app PYTHONUNBUFFERED=1
EXPOSE 5001
CMD ["python3", "run.py"]
