#!/bin/bash
# Docker工具配置脚本

echo "=== Docker工具配置指南 ==="
echo ""
echo "1. 配置Docker工具"
echo "   路径: Jenkins -> 管理Jenkins -> 全局工具配置"
echo "   添加Docker安装:"
echo "   - 名称: Docker"
echo "   - 安装目录: /usr/local/bin/docker"
echo "   - 或选择自动安装最新版本"
echo ""
echo "2. 配置Docker Cloud (可选)"
echo "   路径: Jenkins -> 管理Jenkins -> 节点和云 -> 配置云"
echo "   添加Docker Cloud:"
echo "   - Docker Host URI: unix:///var/run/docker.sock"
echo "   - 启用: 是"
echo ""
echo "3. 安装Docker相关插件"
echo "   推荐插件:"
echo "   - Docker Plugin"
echo "   - Docker Pipeline"
echo "   - Docker Commons"
echo "   - Docker Build Step"
echo ""
echo "4. 验证Docker配置"
echo "   在Jenkins Pipeline中测试:"
echo "   sh 'docker --version'"
echo "   sh 'docker info'"
echo ""
echo "5. 配置Docker Registry"
echo "   在Pipeline中使用:"
echo "   docker.withRegistry('http://localhost:5001', 'registry-auth') {"
echo "       def image = docker.build('my-app:latest')"
echo "       image.push()"
echo "   }"
