#!/bin/bash
# Jenkins凭据配置脚本

echo "=== Jenkins凭据配置指南 ==="
echo ""
echo "请在Jenkins管理界面中配置以下凭据:"
echo ""
echo "1. Gitea访问Token"
echo "   - 类型: Secret text"
echo "   - ID: gitea-token"
echo "   - 描述: Gitea API Token"
echo "   - Secret: (在Gitea用户设置->应用中生成)"
echo ""
echo "2. Docker Registry认证"
echo "   - 类型: Username with password"  
echo "   - ID: registry-auth"
echo "   - 描述: Docker Registry Auth"
echo "   - Username: admin"
echo "   - Password: (Registry管理员密码)"
echo ""
echo "3. SSH密钥"
echo "   - 类型: SSH Username with private key"
echo "   - ID: ssh-key"
echo "   - 描述: Git SSH Key"
echo "   - Username: git"
echo "   - Private Key: (SSH私钥内容)"
echo ""
echo "配置路径: Jenkins -> 管理Jenkins -> 凭据 -> System -> 全局凭据"
